### PR TITLE
Creted the Skip Login button and the Forgot password functionality

### LINKED ISSUE #46: Forgot Password not working

### PR DESCRIPTION
**Pull request by Wathsara**
**Please provide enough information so that others can review your pull request:**

Created the Email password Reset Functionality and created the Skip Login button in order to ease the development.

**Explain the **details** for making this change. What existing problem does the pull request solve?**

Issue #46 and the Developer has to log to the system to view the inside of the app so that created the skip login button

**Test plan (required)**
Unit Testing Up to Now

**Code formatting**

**Closing issues**

Put `closes #46 ` in your comment and commit message to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

File: app/screens/ForgotPasswordScreen/forgotPasswordScreen.js [hunk 1]
```diff
@@ -61,7 +61,12 @@ export default class ForgotPasswordScreen extends Component {
     resetPassword = () => {
         // alert(this.state.email);
```
Comment (shehand) [inline app/screens/ForgotPasswordScreen/forgotPasswordScreen.js]: remove this comment
